### ISSUE TITLE
Componente v-expansion-panel

### ISSUE THREAD

**Issue by aduranti** [vuejs-br/comunidades#14]
Boa tarde pessoal !!

Sou novo na programação com vue, e tenho algumas duvida, mas uma delas é em relação ao componente v-expansion-panel. Achei um exemplo na internet que gostaria de implementar como componente na minha aplicação, mas não tem jeito de funcionar , já fiz igualzinho, já tentei mudar mas não tive nenhum sucesso. Ele não contrai e nem expande..  :(

Se alguem puder ajudar agradeço, este é o exemplo:

https://codepen.io/DedicatedManager/pen/rryymQ

**Comment by ErickPetru** [comment]
Olá @aduranti não utilizamos este repositório para tirar dúvidas, favor entrar em algumas das comunidades aqui listadas para conversar com a galera e expor sua dúvida.
