### ISSUE TITLE
Abrir uma comunidade no Discord

### ISSUE THREAD

**Issue by KuryKat** [vuejs-br/comunidades#15]
# Porquê ?

O Discord é uma das maiores plataformas de comunicação entre pessoas atualmente, superando WhatsApp e até mesmo o Telegram, diversas pessoas que utilizam o Discord não possuem (ou talvez não possam possuir, como é meu caso) um Telegram mas que queria uma comunidade de Vue para compartilhar/ganhar conhecimentos, então venho aqui pedir que vocês façam uma comunidade no Discord, caso tenham interesse, eu posso auxiliar se não conhecerem bem a plataforma, possuo bastante experiência com o aplicativo, agradeço pela atenção, podemos discutir mais sobre isso abaixo!

Link do Discord === [https://discord.com/](https://discord.com/)
Meu discord: [Kurumi Tokisaki#7872](https://discord.com/users/367425061122211843)

Att, [KuryKat](https://github.com/KuryKat)

**Comment by ErickPetru** [comment]
Olá @KuryKat, já temos comunidade no Discord há algum tempo: https://discord.gg/ShSPDE6z. Passou despercebido que ela não estava listada aqui no `README.md`. Obrigado pelo aviso, agora já está lá.
