### ISSUE TITLE
Link do Discord incorreto

### ISSUE THREAD

**Issue by KuryKat** [vuejs-br/comunidades#17]
Provavelmente vocês criaram um link de 24 horas, então ele está inválido:
![link-inválido](https://i.imgur.com/ovdjIse.png)

Peço que escolham um link infinito na hora de criar um!

## Pequeno Guia:

- Clique em convidar amigos na parte de opções do servidor (botão direito em cima do servidor)
![passo-1](https://i.imgur.com/ZuGlv2n.png)

- Você vai perceber que o link que ele gera expira em 24 horas automaticamente, selecione a parte de editar link.
![passo-2](https://i.imgur.com/fpgvJBe.png)

- Selecione para que ele seja infinito! 
![passo-3](https://i.imgur.com/pjoy1fs.png)

- E aqui para que possam entrar infinitas pessoas!
![passo-4](https://i.imgur.com/zn5uHCW.png)

- Se você quiser pode selecionar para que possam existir membros temporários.
- Dai basta apertar em Gerar Novo Link!
![passo-5](https://i.imgur.com/bSoN3Hy.png)

- Prontinho! Novo link gerado e infinito, pronto pra ser adicionado aqui no GitHub e compartilhado com todos os amigos!
![passo-6](https://i.imgur.com/o8FplBl.png)

**Comment by ErickPetru** [comment]
Agradeço a ajuda, não sou usuário adepto do Discord, não sabia que o _link_ padrão expirava. O novo já foi atualizado no `README.md`: https://discord.gg/9P6U3Zufxx.
