### ISSUE TITLE
O que há de errado aqui?

### ISSUE THREAD

**Issue by marcellopato** [vuejs-br/comunidades#19]
I've been reading on the internet, all forums and communities, that are some issues with Vite+VueJS3 at the `.mount("#app")` point. I am facing this exactly problem and can't figure how to fix it!

`Uncaught DOMException: String contains an invalid character pointing to app.mount('#app'); at app.js.`

Let's see some code: vite.config.js
```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/sass/app.scss',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
        vue({
            template: {
                transformAssetUrls: {
                    base: null,
                    includeAbsolute: false,
                },
            },
        }),
    ],
    resolve: {
        alias: {
            'vue': 'vue/dist/vue.esm-bundler.js',
        },
    },
});
```

`app.js`
```
import { createApp } from 'vue';
import Lead from './components/Lead.vue';
import Atendimento from './components/Atendimento.vue';

const app = createApp({
  components: {
    Lead,
    Atendimento,
    render: h => h(app)
  }
});

app.component('atendimento', Atendimento);
app.component('lead', Lead);
app.mount('#app');
```

The app.blade.php witch all Blade extends has the <div id="app"> clearly, so there is no problem (I guess) with disposition of the script.

You can see, at `vite.config.js` that there is an alias pointing to the dev compiler:
```
resolve: {
        alias: {
            'vue': 'vue/dist/vue.esm-bundler.js',
        },
    },
```

Right now, I am pulling all my hair out of my head! Can anyone help me? Thanks in advance!

**Comment by ErickPetru** [comment]
Olá @marcellopato, este repositório existe para listar comunidades Vue por todo o Brasil, e seus canais de comunicação.

Entretanto, postar dúvidas diretamente aqui, além de não ser a intenção do repositório, dificilmente gerará o resultado que você espera, que é alguém te ajudar com seu problema.

Recomendo pelas comunidades aqui apresentadas, escolha alguma(s) e envie sua dúvida por lá.
