### ISSUE TITLE
Hangouts quinzenais

### ISSUE THREAD

**Issue by wilcorrea** [vuejs-br/comunidades#5]
Oi pessoal, estava querendo organizar uns hangouts quinzenais. Qual o melhor canal para organizar isso?

**Comment by vinicius73** [comment]
Acho que aqui é o melhor lugar.
Uma issue por hangout, podemos usar os comentários anúncios e resumos 
Interessados só precisam dar um watch no repo e nas issues

**Comment by wilcorrea** [comment]
@vinicius73 consegue me dar autonomia para gerenciar as issues?
