### ISSUE TITLE
Tema do hangouts 21/06/2018

### ISSUE THREAD

**Issue by wilcorrea** [vuejs-br/comunidades#7]
Iae pessoas abrindo para sugestões para o próximo hangouts que acontecerá dia 21/06/2018 às 20h (o horário foi definido na #6 ).

O link para assistir será divulgado e nas redes sociais e telegram.

Quem quiser participar como moderador também sinalize aqui na issue ou me mande mensagens privadas no [t.me/wilcorrea](https://t.me/wilcorrea).

**Comente abaixo qual a sugestão de tema que você acha interessante**!

Caso o tema que você queira já exista pode apenas dar um joinha nele (:+1:)

#### Edições

Link da live: https://www.youtube.com/c/VuejsBrasil/live

Lista de temas que já foram propostos:
a) Utilização de events e props para comunicação entre componentes [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-396330342)
b) Vue lifecycles, boas práticas e exemplos de uso [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-396595196)
c) Trabalhando com Vuex [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-398135440)
d) Utilizando Vue com Webpack [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-398135916)
e) Vue-cli v3, adicionando alias e loaders com vue.config [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-398137786)
f) Arquitetura e estruturação de projeto (pastas, componentes, módulos, store, etc.) [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-398137921)
g) Vuetify [ir para](https://github.com/vuejs-br/comunidades/issues/7#issuecomment-398161693)

**Comment by wilcorrea** [comment]
Utilização de `events` e `props` para comunicação entre `componentes`

**Comment by emtudo** [comment]
updated () {}

mas que não seja a única coisa, pq isso levaria apenas alguns minutos.

'o tema seria "vue lifecycles,  boas práticas e exemplos de uso"'

Título do tema copiado de Brun00

**Comment by IgorDePaula** [comment]
Vuex, seria um tema avançado?

**Comment by tonimota** [comment]
Acho que seria legal falarem sobre o webpack e como trabalhar ele para funcionar bem com o Vue... Ou talvez essa sugestão fosse mais para um hangouts de Webpack haha

**Comment by BlackMix** [comment]
Vue-cli v3, adicionando alias e loaders com vue.config,
para quem quer usar a nova versão.

**Comment by marceloavf** [comment]
**Tema proposto:** Arquitetura e estruturação de projeto (Pastas, componentes, modulos, store, etc.).

**Comment by wilcorrea** [comment]
Acho que depende da forma com que se aborda @IgorDePaula. Vuex pode ser bem básico ou bem complexo... Na prática é uma lib do ecossistema do Vue (assim como o Router) e vale um hangouts sobre o tema certamente : )

**Comment by silvadeoliveira** [comment]
Vamos em um tema básico até o avançado um série de hangout em etapas por exemplo

**Comment by TL-Developer** [comment]
Seria legal também Vuetify.

**Comment by felipecesr** [comment]
Como faço para participar do hangout?

**Comment by wilcorrea** [comment]
Participar ou assistir @felipecesr ?

**Comment by wilcorrea** [comment]
Parece uma boa ideia @silvadeoliveira :+1:

**Comment by felipecesr** [comment]
Assistir @wilcorrea.

**Comment by wilcorrea** [comment]
Vamos divulgar o link aqui, no twitter, no telegram, etc, é só ficar atento @felipecesr : )

**Comment by felipecesr** [comment]
blz, valeu!

**Comment by hamiltongabriel** [comment]
vue-router, acho que muitos ainda nao tem uma compreensao de como trabalhar, e tambem dar uma pincelada por cima do Event.$bus.

**Comment by luiguild** [comment]
Construção de Plugins e porque usa-los ao invés de ficar importando as paradas mil vezes

**Comment by luiguild** [comment]
'Encontrei o pacote X na NPM e encontrei vue-X, qual devo usar?' sobre leitura de código e atenção necessária em usar abstrações achando que vão facilitar sua vida

**Comment by luiguild** [comment]
'Já sei o suficiente sobre Vuex e agora decidi criar módulos': Como e por que usar namespaced e boas práticas específicas para utilização de mapGetters e mapActions com módulos

**Comment by IgorHalfeld** [comment]
Vue-cli v3 seria :top: D+

**Comment by wilcorrea** [comment]
Dando um up no link https://www.youtube.com/c/VuejsBrasil/live

**Comment by nwrox** [comment]
@wilcorrea vai ficar gravado para depois?

**Comment by wilcorrea** [comment]
@nwrox vai sim, este mesmo link do YT ali : )

**Comment by wilcorrea** [comment]
A opção de trazer novos temas por aqui foi encerrada.
Os 4 mais votados vão para uma seleção no facebook para somar votos com os que fora votados aqui
```
Votos - Tema
11 - Arquitetura e estruturação de projeto (pastas, componentes, módulos, store, etc.)
10 - Utilização de events e props para comunicação entre componentes
06 - Vue lifecycles, boas práticas e exemplos de uso
02 - Encontrei o pacote X na NPM e encontrei vue-X, qual devo usar?
```

**Comment by ktquez** [comment]
Link da enquete no Facebook
[fb.com/vuejsbrasil/enquete](https://www.facebook.com/groups/vuejsbr/permalink/1814476842194902/)
